# select base image as node:alpine
FROM node:alpine
# create an app folder inside the container
WORKDIR '/app'
# copy package.json file inside app folder from work directory
COPY ./package.json ./
# Run npm install command
RUN npm install
# copy all source code from work directory to app folder in container
COPY . .
# run startup command
CMD [ "npm","run","start" ]
